# Neural Network learning

In [1]:
import pandas as pd
import numpy as np
import random
import re

import keras
from keras import models
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from sklearn import preprocessing
from tensorflow.keras.models import load_model
import tensorflow as tf
from sklearn.model_selection import train_test_split, cross_val_score

Using TensorFlow backend.

In [2]:
quant_pers = pd.read_csv(r'../data/quant_personalities.csv')

In [3]:
quant_pers.head()

,Unnamed: 0,type,length_comment,var_length,links_count,qm_count,exm_count,img_count,music_count,dots_count,ht_count,me_count,I-E,N-S,T-F,J-P
0,0,INFJ,11.12,0.179750,0.48,0.36,0.06,0.12,0.02,0.30,0.0,1.18,1,0,0,0
1,1,ENTP,23.40,0.184469,0.20,0.10,0.00,0.02,0.00,0.38,0.0,3.06,0,0,1,1
2,2,INTP,16.72,0.184010,0.10,0.24,0.08,0.00,0.00,0.26,0.0,1.44,1,0,1,1
3,3,INTJ,21.28,0.186640,0.04,0.22,0.06,0.00,0.02,0.52,0.0,2.18,1,0,1,0
4,4,ENTJ,19.34,0.178723,0.12,0.20,0.02,0.04,0.02,0.42,0.0,1.48,0,0,1,0

In [6]:
sep_targets = quant_pers.copy()

In [16]:
# build model

In [17]:
# neural network and accuracy in whole

In [4]:
quant_pers = quant_pers.drop(columns = "Unnamed: 0")

In [5]:
quant_pers['type'] = quant_pers['type'].astype('category')
quant_pers['type'] = quant_pers['type'].cat.codes

,type,length_comment,var_length,links_count,qm_count,exm_count,img_count,music_count,dots_count,ht_count,me_count,I-E,N-S,T-F,J-P
0,8,11.12,135.2900,0.48,0.36,0.06,0.12,0.02,0.30,0.0,1.18,I,N,F,J
1,3,23.40,187.4756,0.20,0.10,0.00,0.02,0.00,0.38,0.0,3.06,E,N,T,P
2,11,16.72,180.6900,0.10,0.24,0.08,0.00,0.00,0.26,0.0,1.44,I,N,T,P
3,10,21.28,181.8324,0.04,0.22,0.06,0.00,0.02,0.52,0.0,2.18,I,N,T,J
4,2,19.34,196.4576,0.12,0.20,0.02,0.04,0.02,0.42,0.0,1.48,E,N,T,J

In [44]:
y = pd.DataFrame(quant_pers['type'])
X = quant_pers.drop(columns=['type','I-E', 'N-S', 'J-P', 'T-F']).copy()

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=124)

In [ ]:
# X_train = tf.keras.utils.normalize(X_train, axis = 1)

In [46]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6940 entries, 7502 to 4558
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   length_comment  6940 non-null   float64
 1   var_length      6940 non-null   float64
 2   links_count     6940 non-null   float64
 3   qm_count        6940 non-null   float64
 4   exm_count       6940 non-null   float64
 5   img_count       6940 non-null   float64
 6   music_count     6940 non-null   float64
 7   dots_count      6940 non-null   float64
 8   ht_count        6940 non-null   float64
 9   me_count        6940 non-null   float64
dtypes: float64(10)
memory usage: 596.4 KB

In [ ]:
val_loss, val_acc = voices_new_model.evaluate(X_new_test, y_new_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')

In [49]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=256, kernel_initializer='uniform', activation='relu', input_dim=10))
model.add(tf.keras.layers.Dense(units=128, kernel_initializer='uniform', activation='relu'))
model.add(tf.keras.layers.Dense(units=64, kernel_initializer='uniform', activation='relu'))
model.add(tf.keras.layers.Dense(activation = 'sigmoid', units = 1, kernel_initializer = 'uniform')) # output layer has number of outputs not number of neurons

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# calculating loss, model is always trying to minimize loss, adam is the default optimize


model.fit(X_train, y_train, epochs = 10, batch_size= 25)

val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')

Epoch 1/10
278/278 [==============================] - 1s 4ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 2/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 3/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 4/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 5/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 6/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225: 0s - loss: 9.8123e-07 - accuracy:
Epoch 7/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 8/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 9/10
278/278 [==============================] - 1s 2ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Epoch 10/10
278/278 [==============================] - 1s 3ms/step - loss: 9.7968e-07 - accuracy: 0.0225
Test loss: 9.869979749055346e-07
Test accuracy: 0.019596541300415993

In [48]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss, val_acc)

55/55 [==============================] - 0s 2ms/step - loss: 9.8700e-07 - accuracy: 0.0202
9.869979749055346e-07 0.020172910764813423

In [ ]:
# neural network on seperate targets

In [9]:
data2 = sep_targets.drop(columns = ['type'])
data2.head()

,length_comment,var_length,links_count,qm_count,exm_count,img_count,music_count,dots_count,ht_count,me_count,I-E,N-S,T-F,J-P
0,11.12,0.179750,0.48,0.36,0.06,0.12,0.02,0.30,0.0,1.18,1,0,0,0
1,23.40,0.184469,0.20,0.10,0.00,0.02,0.00,0.38,0.0,3.06,0,0,1,1
2,16.72,0.184010,0.10,0.24,0.08,0.00,0.00,0.26,0.0,1.44,1,0,1,1
3,21.28,0.186640,0.04,0.22,0.06,0.00,0.02,0.52,0.0,2.18,1,0,1,0
4,19.34,0.178723,0.12,0.20,0.02,0.04,0.02,0.42,0.0,1.48,0,0,1,0

In [51]:
#data2['I-E'] = data2['I-E'].astype('category')
#data2['N-S'] = data2['N-S'].astype('category')
#data2['T-F'] = data2['T-F'].astype('category')
#data2['J-P'] = data2['J-P'].astype('category')

#cat_columns = data2.select_dtypes(['category']).columns

# data2[cat_columns] = data2[cat_columns].apply(lambda x: x.cat.codes)

In [10]:
X = data2.drop(columns = ['I-E', 'N-S' , 'T-F', 'J-P'])

y_IE = data2['I-E']
y_NS = data2['N-S']
y_TF = data2['T-F']
y_JP = data2['J-P']

In [11]:
 # X = tf.keras.utils.normalize(X, axis = 1)

In [12]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=256, kernel_initializer='uniform', activation='relu', input_dim=10))
model.add(tf.keras.layers.Dense(units=128, kernel_initializer='uniform', activation='relu'))
model.add(tf.keras.layers.Dense(units=64, kernel_initializer='uniform', activation='relu'))
model.add(tf.keras.layers.Dense(activation = 'sigmoid', units = 1, kernel_initializer = 'uniform')) # output layer has number of outputs not number of neurons

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# calculating loss, model is always trying to minimize loss, adam is the default optimize


# model.fit(X_train, y_train, epochs = 10, batch_size= 25)

# val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
# print(f'Test loss: {val_loss}')
# print(f'Test accuracy: {val_acc}')

In [14]:


# IE
X_train, X_test, y_train, y_test = train_test_split(X, y_IE, test_size=0.2, random_state=10)
model.fit(X_train, y_train, epochs = 10, batch_size= 25)
predmodel = model.predict(x_test)
print("I-E RESULTS")
# print("Confusion Matrix for Multinomial Naive Bayes:")
# print(confusion_matrix(y_test,predmodel))
# print("Score:",round(accuracy_score(y_test,predmodel)*100,2))
# print("Classification Report:",classification_report(y_test,predmodel))
val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')
print("*" * 100)

# NS
X_train, X_test, y_train, y_test = train_test_split(X, y_NS, test_size=0.2, random_state=10)
model.fit(X_train, y_train, epochs = 10, batch_size= 25)
predmodel = model.predict(x_test)
print("N-S RESULTS")
# print("Confusion Matrix for Multinomial Naive Bayes:")
# print(confusion_matrix(y_test,predmodel))
# print("Score:",round(accuracy_score(y_test,predmodel)*100,2))
# print("Classification Report:",classification_report(y_test,predmodel))
val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')
print("*" * 100)

# TF
X_train, X_test, y_train, y_test = train_test_split(X, y_TF, test_size=0.2, random_state=10)
model.fit(X_train, y_train, epochs = 10, batch_size= 25)
predmodel = model.predict(x_test)
print("T-F Results")
# print("Confusion Matrix for Multinomial Naive Bayes:")
# print(confusion_matrix(y_test,predmodel))
# print("Score:",round(accuracy_score(y_test,predmodel)*100,2))
# print("Classification Report:",classification_report(y_test,predmodel))
val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')
print("*" * 100)

# JP
X_train, X_test, y_train, y_test = train_test_split(X, y_JP, test_size=0.2, random_state=10)
model.fit(X_train, y_train, epochs = 10, batch_size= 25)
predmodel = model.predict(x_test)
print("J-P Results")
# print("Confusion Matrix for Multinomial Naive Bayes:")
# print(confusion_matrix(y_test,predmodel))
# print("Score:",round(accuracy_score(y_test,predmodel)*100,2))
# print("Classification Report:",classification_report(y_test,predmodel))
val_loss, val_acc = model.evaluate(X_test, y_test, verbose=0)
print(f'Test loss: {val_loss}')
print(f'Test accuracy: {val_acc}')
print("*" * 100)

Epoch 1/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 2/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 3/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 4/10
278/278 [==============================] - 1s 4ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 5/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677: 0s - loss: 9.287
Epoch 6/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 7/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 8/10
278/278 [==============================] - 1s 3ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 9/10
278/278 [==============================] - 1s 5ms/step - loss: 9.1520e-08 - accuracy: 0.7677
Epoch 10/10
278/278 [==============================] - 2s 8ms/step - loss: 9.1520e-08 - accuracy: 0.7677
I-E RESULTS
Test loss: 9.261908928692719e-08
Test accuracy: 0.7769452333450317
****************************************************************************************************
Epoch 1/10
278/278 [==============================] - 1s 3ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 2/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 3/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 4/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 5/10
278/278 [==============================] - 2s 6ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 6/10
278/278 [==============================] - 1s 3ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 7/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366: 0s - loss: 1.677
Epoch 8/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 9/10
278/278 [==============================] - 1s 4ms/step - loss: 1.6284e-08 - accuracy: 0.1366
Epoch 10/10
278/278 [==============================] - 2s 6ms/step - loss: 1.6284e-08 - accuracy: 0.1366
N-S RESULTS
Test loss: 1.710842312263594e-08
Test accuracy: 0.14351585507392883
****************************************************************************************************
Epoch 1/10
278/278 [==============================] - 1s 4ms/step - loss: 5.4829e-08 - accuracy: 0.4599: 0s - loss:
Epoch 2/10
  1/278 [..............................] - ETA: 0s - loss: 6.6757e-08 - accuracy: 0.5600WARNING:tensorflow:Method (on_train_batch_end) is slow compared to the batch update (0.119151). Check your callbacks.
278/278 [==============================] - 2s 7ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 3/10
278/278 [==============================] - 1s 4ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 4/10
278/278 [==============================] - 1s 4ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 5/10
278/278 [==============================] - 1s 4ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 6/10
278/278 [==============================] - 1s 4ms/step - loss: 5.4829e-08 - accuracy: 0.4599:
Epoch 7/10
278/278 [==============================] - 1s 5ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 8/10
278/278 [==============================] - 1s 5ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 9/10
278/278 [==============================] - 1s 5ms/step - loss: 5.4829e-08 - accuracy: 0.4599
Epoch 10/10
278/278 [==============================] - 1s 5ms/step - loss: 5.4829e-08 - accuracy: 0.4599
T-F Results
Test loss: 5.421102500235975e-08
Test accuracy: 0.454755038022995
****************************************************************************************************
Epoch 1/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 2/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 3/10
278/278 [==============================] - 1s 5ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 4/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 5/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 6/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 7/10
278/278 [==============================] - 1s 5ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 8/10
278/278 [==============================] - ETA: 0s - loss: 7.2296e-08 - accuracy: 0.60 - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 9/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
Epoch 10/10
278/278 [==============================] - 1s 4ms/step - loss: 7.2230e-08 - accuracy: 0.6059
J-P Results
Test loss: 7.118202915989968e-08
Test accuracy: 0.5971181392669678
****************************************************************************************************