In [1]:
import pandas as pd
import numpy as np
import re

# Barcelona

In [2]:
bcn=pd.read_csv('../data/barcelona_data.csv')

In [3]:
bcn.drop(bcn[bcn['Price']=='€\xa0666666'].index, inplace=True)
bcn.drop(bcn[bcn['Pets']=='0'].index, inplace=True)
bcn_list=bcn['Pets'].tolist()
symbol = '\n'
bcn_list_clean=[item.translate(symbol).strip() for item in bcn_list]
bcn.drop(['Pets'],axis=1, inplace=True)
bcn['Pets'] = bcn_list_clean
bcn.drop(['Unnamed: 0'],axis=1, inplace=True)
bcn_prices=bcn['Price'].tolist()

clean_prices=[]
for i in bcn_prices:
    clean_prices.append(re.findall(r"\b[0-9]+\b",i)[0])
    
bcn.drop(['Price'],axis=1, inplace=True)
bcn['Price'] = clean_prices
bcn = bcn[['Name', 'Score', 'Price', 'Pets', 'Link']]

In [4]:
bcn.insert(0, 'City', 'Barcelona')
bcn

,City,Name,Score,Price,Pets,Link
0,Barcelona,El Avenida Palace,8.8,111,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/es/w-barcelona.e...
1,Barcelona,W Barcelona,8.5,256,Pets are not allowed.,https://www.booking.com/hotel/es/negresco-prin...
2,Barcelona,Negresco Princess 4* Sup,8.3,77,Pets are not allowed.,https://www.booking.com/hotel/es/h10-cubik.en-...
3,Barcelona,Novotel Barcelona City,8.3,69,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/es/avenidapalace...
4,Barcelona,Ayre Hotel Rosellón,8.8,74,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/es/diagonal-zero...
...,...,...,...,...,...,...
494,Barcelona,Ramblas by Pillow,8.8,95,Pets are not allowed.,https://www.booking.com/hotel/es/royal-passeig...
495,Barcelona,Aparthotel Bonanova,8.3,111,Pets are not allowed.,https://www.booking.com/hotel/es/bcn-montjuic....
496,Barcelona,Factory Suites Barcelona,8.8,139,Free!\nPets are allowed. No extra charges.,https://www.booking.com/hotel/es/kimpton-barce...
497,Barcelona,Boat Hotel Barcelona,9.3,211,Pets are not allowed.,https://www.booking.com/hotel/es/gran-via-678....
499,Barcelona,Chic & Basic Lemon Boutique Hotel,8.9,69,Pets are not allowed.,https://www.booking.com/hotel/es/vinccimaritim...

# Amsterdam

In [5]:
amst=pd.read_csv('../data/amsterdam_data.csv')

In [6]:
amst.drop(amst[amst['Price']=='€\xa0666666'].index, inplace=True)
amst.drop(amst[amst['Pets']=='0'].index, inplace=True)
amst_pets=amst['Pets'].tolist()
symbol = '\n'
amst_pets_clean=[item.translate(symbol).strip() for item in amst_pets]
amst.drop(['Pets'],axis=1, inplace=True)
amst['Pets'] = amst_pets_clean
amst_prices=amst['Price'].tolist()

clean_amst_prices=[]
for i in amst_prices:
    clean_amst_prices.append(re.findall(r"\b[0-9]+\b",i)[0])
    
amst.drop(['Price'],axis=1, inplace=True)
amst['Price'] = clean_amst_prices
amst = amst[['Name', 'Score', 'Price', 'Pets', 'Link']]

In [7]:
amst.insert(0, 'City', 'Amsterdam')
amst

,City,Name,Score,Price,Pets,Link
0,Amsterdam,Park Plaza Victoria Amsterdam,8.4,175,Pets are not allowed.,https://www.booking.com/hotel/nl/victoria.en-g...
1,Amsterdam,Park Inn by Radisson Amsterdam City West,8.3,130,Pets are not allowed.,https://www.booking.com/hotel/nl/monet-garden-...
2,Amsterdam,"Radisson Blu Hotel, Amsterdam City Center",8.5,225,Pets are not allowed.,https://www.booking.com/hotel/nl/mai-amsterdam...
5,Amsterdam,Monet Garden Hotel Amsterdam,9.0,175,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/nl/nhamsterdam.e...
6,Amsterdam,NH City Centre Amsterdam,8.3,162,Pets are not allowed.,https://www.booking.com/hotel/nl/pestana-amste...
...,...,...,...,...,...,...
492,Amsterdam,B&B Amsterdam De Springer,9.6,153,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/nl/holiday-inn-e...
493,Amsterdam,B&B Mondriaan,8.0,145,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/nl/the-hoxton-am...
494,Amsterdam,The Quay Amsterdam-Noord - FREE PARKING,9.3,314,Pets are not allowed.,https://www.booking.com/hotel/nl/radissonamste...
496,Amsterdam,Bed & Breakfast Diemerbrug,9.8,155,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/nl/jollycarlton....
497,Amsterdam,Fenelli BnB,9.4,138,Pets are not allowed.,https://www.booking.com/hotel/nl/library-amste...

# Lisabon

In [8]:
lis=pd.read_csv('../data/lisabon_data.csv')

In [9]:
lis.drop(lis[lis['Price']=='€\xa0666666'].index, inplace=True)
lis.drop(lis[lis['Pets']=='0'].index, inplace=True)
lis_pets=lis['Pets'].tolist()
symbol = '\n'
lis_pets_clean=[item.translate(symbol).strip() for item in lis_pets]
lis.drop(['Pets'],axis=1, inplace=True)
lis['Pets'] = lis_pets_clean

lis_prices=lis['Price'].tolist()

clean_lis_prices=[]
for i in lis_prices:
    clean_lis_prices.append(re.findall(r"\b[0-9]+\b",i)[0])
    
lis.drop(['Price'],axis=1, inplace=True)
lis['Price'] = clean_lis_prices
lis =lis[['Name', 'Score', 'Price', 'Pets', 'Link']]

In [10]:
lis.insert(0, 'City', 'Lisabon')
lis

,City,Name,Score,Price,Pets,Link
0,Lisabon,Lisboa Carmo Hotel,9.2,85,Pets are not allowed.,https://www.booking.com/hotel/pt/lux-lisboa-pa...
1,Lisabon,H10 Duque de Loule,9.0,67,Pets are not allowed.,https://www.booking.com/hotel/pt/hotelmundial....
2,Lisabon,Hotel Mundial,8.4,97,Pets are not allowed.,https://www.booking.com/hotel/pt/h10-duque-de-...
3,Lisabon,Iberostar Selection Lisboa,8.8,144,Pets are not allowed.,https://www.booking.com/hotel/pt/corpo-santo.e...
4,Lisabon,Corpo Santo Lisbon Historical Hotel,9.5,137,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/pt/the-one-palac...
...,...,...,...,...,...,...
495,Lisabon,Varandas de Lisboa - Tejo River Apartments & R...,9.2,94,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/pt/tryp-lisboa-a...
496,Lisabon,Sky Beds Lisbon,8.0,72,Pets are not allowed.,https://www.booking.com/hotel/pt/upon-lisbon-r...
497,Lisabon,Blue Budget Apartments Bairro Alto,7.4,94,Pets are not allowed.,https://www.booking.com/hotel/pt/memmo-princip...
498,Lisabon,Casa Boma Lisboa - Unique Apartment With Priva...,9.4,172,Pets are not allowed.,https://www.booking.com/hotel/pt/chiado-arty-f...
499,Lisabon,Unique Lisbon Rooms,8.4,33,Pets are not allowed.,https://www.booking.com/hotel/pt/empire-lisbon...

# Paris

In [11]:
prs=pd.read_csv('../data/new_paris_data.csv')

In [12]:
prs.drop(prs[prs['Price']=='€\xa0666666'].index, inplace=True)
prs.drop(prs[prs['Pets']=='0'].index, inplace=True)
prs_pets=prs['Pets'].tolist()
symbol = '\n'
prs_pets_clean=[item.translate(symbol).strip() for item in prs_pets]
prs.drop(['Pets'],axis=1, inplace=True)
prs['Pets'] = prs_pets_clean

prs_prices=prs['Price'].tolist()

clean_prs_prices=[]
for i in prs_prices:
    clean_prs_prices.append(re.findall(r"\b[0-9]+\b",i)[0])
    
prs.drop(['Price'],axis=1, inplace=True)
prs['Price'] = clean_prs_prices
prs =prs[['Name', 'Score', 'Price', 'Pets', 'Link']]

In [13]:
prs.insert(0, 'City', 'Paris')
prs

,City,Name,Score,Price,Pets,Link
0,Paris,Hotel Trianon Rive Gauche,8.3,107,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/fr/tour-eiffel.e...
1,Paris,Elysées Union,8.4,162,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/fr/hyatt-regency...
2,Paris,Résidence Charles Floquet,9.0,262,Pets are not allowed.,https://www.booking.com/hotel/fr/elyseesunion....
3,Paris,Elysées Ceramic,8.4,152,Pets are not allowed.,https://www.booking.com/hotel/fr/citizenm-pari...
4,Paris,Citadines Saint-Germain-des-Prés Paris,8.3,180,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/fr/lutetia-paris...
...,...,...,...,...,...,...
495,Paris,hotelF1 Paris Porte de Châtillon,7.4,56,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/fr/ha-tel-plaza-...
496,Paris,Le Glam's Hotel,8.1,174,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/fr/hotelparismon...
497,Paris,Villa Margaux Opéra Montmartre,7.6,123,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/fr/corona.en-gb....
498,Paris,Hôtel Da Vinci & Spa,8.9,226,Pets are not allowed.,https://www.booking.com/hotel/fr/hotelterminus...
499,Paris,Hôtel Thérèse,8.9,402,Pets are not allowed.,https://www.booking.com/hotel/fr/terminus-vaug...

# Rome

In [14]:
rome=pd.read_csv('../data/rome_data.csv')

In [15]:
rome.drop(rome[rome['Price']=='€\xa0666666'].index, inplace=True)
rome.drop(rome[rome['Pets']=='0'].index, inplace=True)
rome_pets=rome['Pets'].tolist()
symbol = '\n'
rome_pets_clean=[item.translate(symbol).strip() for item in rome_pets]
rome.drop(['Pets'],axis=1, inplace=True)
rome['Pets'] = rome_pets_clean

rome_prices=rome['Price'].tolist()

clean_rome_prices=[]
for i in rome_prices:
    clean_rome_prices.append(re.findall(r"\b[0-9]+\b",i)[0])
    
rome.drop(['Price'],axis=1, inplace=True)
rome['Price'] = clean_rome_prices
rome =rome[['Name', 'Score', 'Price', 'Pets', 'Link']]

In [16]:
rome.insert(0, 'City', 'Rome')
rome

,City,Name,Score,Price,Pets,Link
0,Rome,Hotel Savoy,8.4,137,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/it/giolli.en-gb....
1,Rome,Auditorium Mecenate,8.7,68,Pets are not allowed.,https://www.booking.com/hotel/it/suitesistina....
2,Rome,Hotel Giolli Nazionale,8.4,109,Pets are not allowed.,https://www.booking.com/hotel/it/condotti.en-g...
3,Rome,Hotel Delle Nazioni,8.5,192,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/it/trevi-b-b-rom...
4,Rome,Hotel Patria,7.9,87,Pets are allowed. Charges may be applicable.,https://www.booking.com/hotel/it/donna-camilla...
...,...,...,...,...,...,...
495,Rome,Mia Resort,8.2,76,Free!\nPets are allowed on request. No extra c...,https://www.booking.com/hotel/it/pantheon-inn....
496,Rome,Termini Terrace,8.9,70,Pets are not allowed.,https://www.booking.com/hotel/it/residenza-pao...
497,Rome,Hotel Touring,7.8,65,Pets are not allowed.,https://www.booking.com/hotel/it/delle-nazioni...
498,Rome,Hotel dei Barbieri,8.7,167,Pets are allowed on request. Charges may be ap...,https://www.booking.com/hotel/it/albergo-abruz...
499,Rome,Aventino Guest House,9.0,83,Pets are not allowed.,https://www.booking.com/hotel/it/mia-suites.en...

# Appending dataframes

In [17]:
bcn_amst=bcn.append(amst)
bcn_amst_lis=bcn_amst.append(lis)
bcn_amst_lis_prs=bcn_amst_lis.append(prs)
data=bcn_amst_lis_prs.append(rome)

In [18]:
data['City'].value_counts()

Paris        500
Rome         496
Lisabon      473
Barcelona    469
Amsterdam    437
Name: City, dtype: int64

In [19]:
data.to_csv('booking_pets_data_with_rome.csv')